{% set version = "0.3.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-pkggraphr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/pkgGraphR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/pkgGraphR/pkgGraphR_{{ version }}.tar.gz
  sha256: 29c2790f256538d70db545af3a5f3f5357d60266186c87b4a8c4e918cf46bc1d

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-diagrammer
    - r-dplyr
    - r-purrr
  run:
    - r-base
    - r-diagrammer
    - r-dplyr
    - r-purrr

test:
  commands:
    - $R -e "library('pkgGraphR')"           # [not win]
    - "\"%R%\" -e \"library('pkgGraphR')\""  # [win]

about:
  home: https://gitlab.com/doliv071/pkggraphr
  license: GPL-3.0-or-later
  summary: It is often useful when developing an R package to track the relationship between functions in order to appropriately test and track changes. This package generates a graph of the relationship between all R functions in a package. It can also be used on any directory containing .R files which can be very useful
    for 'shiny' apps or other non-package workflows.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - thewchan

# Package: pkgGraphR
# Type: Package
# Title: Graph the Relationship Between Functions in an R Package
# Version: 0.2.0
# Authors@R: person(given = "David", family = "Oliver", email = "doliv071@gmail.com", role = c("aut", "cre","cph"))
# Maintainer: David Oliver <doliv071@gmail.com>
# BugReports: https://gitlab.com/doliv071/pkggraphr/-/issues
# URL: https://gitlab.com/doliv071/pkggraphr
# Description: It is often useful when developing an R package to track the relationship between functions in order to appropriately test and track changes. This package generates a graph of the relationship between all R functions in a package. It can also be used on any directory containing .R files which can be very useful for 'shiny' apps or other non-package workflows.
# License: GPL (>= 3)
# Encoding: UTF-8
# RoxygenNote: 7.3.1
# Imports: DiagrammeR, dplyr, purrr, stats, utils
# Suggests: knitr, rmarkdown, testthat (>= 3.0.0)
# Config/testthat/edition: 3
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2024-04-01 17:15:14 UTC; oliverd
# Author: David Oliver [aut, cre, cph]
# Repository: CRAN
# Date/Publication: 2024-04-02 13:02:04 UTC
